<?php 
// ------------  Menu & tieu de -----------------
@define ('_sach','Book');
@define ('_sanphamdikem','Products included');
@define ('_congtrinh', 'Buildings');
@define ('_vechungtoi','About Us');
@define ('_cuahang', 'Store');
@define ('_congtrinh', 'Buildings');
@define ('_bosuutap', 'Collection');
@define ('_ytuongnoithat', 'Interior ideas');
@define ('_taikhoannganhang', 'Bank account');
@define ('_danhmucsanpham', 'Product Category');
@define ('_nhaptukhoatimkiem', 'Enter search keywords');
@define ('_chuanhaptukhoa', 'No search terms entered');
@define ('_ketquatimkiem', 'Search results');
@define ('_trongdanhmuc', 'In category');
@define ('_thongtinlienhe', 'Contact information');
@define ('_chitiet', 'Details');
@define ('_thongtinthem', 'More information');

@define ('_hinhanh', 'Photos');
@define ('_khachhang', 'Customers');
@define ('_thongtincodong', 'Shareholder Information');
@define ('_trangchu', 'Home');
@define ('_sanpham', 'Products');
@define ('_sanphamchinh','Main products');
@define ('_sanphamnoibat','Hot products');
@define ('_sanphambanchay', 'Best seller');
@define ('_sanphammoi', 'New product');
@define ('_tintuc', 'News');
@define ('_tintucmoi', 'Breaking news');
@define ( '_tintucnoibat', 'Hot news');
@define ('_lienhe', 'Contact');
@define ('_dathietke', 'Designed');
@define ('_gioithieu', 'Introduction');
@define ('_dichvu', 'Services');
@define ('_dangkytuvan', 'Sign up for advice');
@define ('_lienhe', 'Contact');
@define ('_hotrokhachhang', 'Customer support');
@define ('_khongtimthaytrang', 'Page not found');
@define ('_danhmucdichvu', 'Service catalog');
@define ('_cacbaivietkhac', 'Other articles');
@define ('_docbaiviet', 'Read article');
@define ('_xemthem', 'See also');
@define ('_xemthemmauwebsitekhac', 'See more website templates');
@define ('_xemhinhanh', 'View image');
@define ('_xemthucte', 'Actual view');
@define ('_didenwebsite', 'Go to website');
@define ('_ngaydang', 'Posted Date');
@define ('_sanphamcungloai', 'Similar products');
@define ('_tinhuuich', 'Useful news');
@define ('_ykienkhachhang','Customer reviews');
//------------text--------------------------
@define ('_xemchitiet', 'View details');
@define ('_tatcaytuong', 'All ideas');
@define ('_motasanpham', 'Product description');
@define ('_quycach', 'Specification');
@define ('_huongdanbaoquan', 'Storage instructions');
@define ('_diachi', 'Address');
@define ('_ngayhoanthanh', 'Due date');
@define ('_dangchuyentrang', 'Transferring page');
@define ('_gia','Price');
@define ('_giaban','Price');
@define ('_chinhsach', 'Policy');
@define ('_themvaogio', 'Add to cart');
@define ('_themvaogiohang', 'Add to cart');
@define ('_luotxem', 'Views');
@define ('_soluong', 'Quantity');
@define ('_muangaysanphamnay','Buy this product now');
@define ('_camkethangchinhhangthat100','Genuine goods commitment, 100% real');
@define ('_donvitinh', 'Unit of calculation');
@define ('_goingay', 'Call now');
@define ('_decoduocgiatotnhat', 'To get the best price');
@define ('_thongtin', 'Information');
@define ('_danhgia', 'Review');
@define ('_masanpham', 'Product SKU');
@define ('_thanhcong', 'Success');
@define ('_donhanghoantat', 'Order completed');
@define ('_giohang', 'Shopping cart');
@define ('_payment', 'Payment');
@define ('_pname', 'Product name');
@define ('_quantity', 'Quantity');
@define ('_total_price', 'Total price');
@define ('_price', 'Price');
@define ('_ congcu', 'Tool');
@define ('_cus_info', 'Customer information');
@define ('_fullname', 'Full name');
@define ('_phone', 'Phone');
@define ('_address', 'Address');
@define ('_ghichu', 'Note');
@define ('_continue', 'Continue');
@define ('_thongtinnhanhang', 'Receipt information');
@define ('_gingthongtinnguoinhan', 'Like recipient information');
@define ('_thanhtien', 'Money');
@define ('_xacnhanthanhtoan', 'Confirmation and payment');
@define ('_chuaduocgui', 'Your order has not been sent yet');
@define ('_dienthongtin', 'Please fill out the form again');
@define ('_camon', 'Thank you');
@define ('_bandadathangthanhcong', 'You have successfully placed an order.');
@define ('_chungtoiselienhe', 'We will contact you as soon as possible.');
@define ('_madonhang', 'Order number is');
@define ('_xinloiquykhach', 'Sorry, visitor.');
@define ('_hethongbiloixinthulai', 'The system has failed, please try again.');
@define ('_donhangchuacosanpham', 'Your order has no products.');
@define ('_chonsanphamdemuahang', 'Please select the product to order.');
@define ('_chuamuasanpham', 'You have not purchased any products.Please choose to buy the product.');
@define ('_thongtinthanhtoan', 'Payment Information');
@define ('_phuongthucthanhtoan', 'Payment Method');
@define ('_muatiep', 'Buy next');
@define ('_xoatatca', 'Delete all');
@define ('_dathangthanhcong', 'Order successfully');
@define ('_camonquykhachdadathangtai', 'Thank you for ordering at');
@define ('_masodonhangcuabanla', 'Your order number is');
@define ('_tieptucmuahang', 'Continue shopping');
@define ('_dienthoaihotromuahang', 'Phone to purchase support');
@define ('_themsanpham', 'Add product');
@define ('_vaogiohangthanhcong', 'successfully entered into basket');
@define ('_thongtindonhangduocguivemail', "The order details have been sent to the email address you used to place your order. If you can't find it please check your Spam or Junk Folder");
// ------------- form dang ky tu van ------------------

@define ('_hovaten', 'Full name');
@define ('_dienthoai', 'Phone');
@define ('_noidung', 'Content');
@define ('_tinhthanhpho', 'Province / City'); 
@define ('_quanhuyen', 'District');
@define ('_guilienhe', 'Send contact');
@define ('_gui', 'Send');
@define ('_nhaphoten', 'Enter full name');
@define ('_nhapemail', 'Enter Email');
@define ('_emailkhonghople', 'Invalid email');
@define ('_nhapsodienthoai', 'Enter phone number');
@define ('_sodienthoaikhonghople', 'Invalid phone number');
@define ('_chontinhthanhpho', 'Select province / city');
@define ('_chonquanhuyen', 'Select district');
@define ('_nhapdiachi', 'Please enter Address');
@define ('_chondichvu', 'Select service');
@define ('_nhapnoidung', 'Enter text');
@define ('_chuanhapduthongtin', 'You have not entered enough information');
@define ('_guithuthanhcong', 'The information has been sent successfully. <br /> Thank you');
@define ('_guithuthatbai', 'The system is experiencing an error. Please try again later');
@define ('_maxacnhankhongchinhxac', 'The confirmation code is incorrect!');
@define ('_clickvaodayneukhongmuondoilau', "Click here if you don't want to wait long");

// ---------------- box-right ----------------
@define ('_guitinnhan', 'Send message');
@define ('_goichochungtoi', 'Call us');
@define ('_chatqua', 'Chat over');
@define ('_vanphong', 'Office');
@define ('_hotlinetuvan', 'Consulting hotline');
@define ('_delaithongtin', 'Leave information');
@define ('_nhangiauudai', 'Get a discount');
@define ('_sodienthoaicuaban', 'Your phone number');
@define ('_yeucaugoilai', 'Request a callback');
@define ('_delailoinhanchochungtoi', 'Leave a message for us');
@define ('_goicho', 'Call');
@define ('_denhantuvantotnhat', 'to get the best advice');
@define ('_hoac', 'Or');
@define ('_thongbaosetudongtatsau', 'Notifications will automatically turn off later');
@define ('_giay', 'seconds');
@define ('_guithanhcong', 'Send contact successfully');
@define ('_loicamon', 'Thank you for leaving the information. We will contact you as soon as possible.');
@define ('_hethongbiloi', 'System error');
@define ('_quykhachtimlaisau', 'Please try again later.');
@define ('_thongbaokhachguiyeucaugoilai', 'Customer notice sent request to call back');
@define ('_sodienthoai', 'Phone number');
@define ('_thoigiangui', 'Time to send');
@define ('_thongbaokhachguitinnhan', 'Notification to send message');
@define ('_tinnhan', 'Message');
@define ('_goidien','Call');