<?php
//------------ Menu & tieu de-----------------
@define ('_duan','Dự án');
@define ('_cacduankhac','Các dự án khác');
@define ('_sach','Sách');
@define ('_muangay','Mua ngay');
@define ('_cauchuyen','Câu chuyện');
@define ('_bangtin','Bảng tin');
@define ('_thucdon','Thực đơn');
@define ('_tuyendung','Tuyển dụng');

@define ('_sanphamdikem','Sản phẩm đi kèm');
@define ('_congtrinh','Công trình');
@define ('_vechungtoi','Về chúng tôi');
@define ('_cuahang','Cửa hàng');
@define ('_congtrinh','Công trình');
@define ('_bosuutap','Bộ sưu tập');
@define ('_ytuongnoithat','Ý tưởng nội thất');
@define ('_taikhoannganhang','Tài khoản ngân hàng');
@define ('_danhmucsanpham','Danh mục sản phẩm');
@define ('_nhaptukhoatimkiem','Nhập từ khóa tìm kiếm');
@define ('_chuanhaptukhoa','Chưa nhập từ khóa tìm kiếm');
@define ('_ketquatimkiem','Kết quả tìm kiếm');
@define ('_trongdanhmuc','Trong danh mục');
@define ('_thongtinlienhe','Thông tin liên hệ');
@define ('_chitiet','Chi tiết');
@define ('_thongtinthem','Thông tin thêm');

@define ('_hinhanh', 'Hình ảnh');
@define ('_khachhang', 'Khách hàng');
@define ('_thongtincodong','Thông tin cổ đông');
@define ('_trangchu','Trang chủ');
@define ('_sanpham','Sản phẩm');
@define ('_sanphamchinh','Sản phẩm chính');
@define ('_sanphamnoibat','Sản phẩm nổi bật');
@define ('_sanphambanchay','Sản phẩm bán chạy');
@define ('_sanphammoi','Sản phẩm mới');
@define ('_tintuc','Tin tức & Sự Kiện');
@define ( '_tintucmoi', 'Tin tức mới');
@define ( '_tintucnoibat', 'Tin tức nổi bật');
@define ('_lienhe','Liên hệ');
@define ('_dathietke','Đã thiết kế');
@define ('_gioithieu','Giới thiệu');
@define ('_dichvu','Dịch vụ');
@define ('_dangkytuvan','Đăng ký tư vấn');
@define ('_lienhe','Liên hệ');
@define ('_hotrokhachhang','Hỗ trợ khách hàng');
@define ('_khongtimthaytrang','Không tìm thấy trang');
@define ('_danhmucdichvu','Danh mục dịch vụ');
@define ('_cacbaivietkhac','Các bài viết khác');
@define ('_docbaiviet','Đọc bài viết');
@define ('_xemthem','Xem thêm');
@define ('_xemthemmauwebsitekhac','Xem thêm mẫu website khác');
@define ('_xemhinhanh','Xem hình ảnh');
@define ('_xemthucte','Xem thực tế');
@define ('_didenwebsite','Đi đến website');
@define ('_ngaydang','Ngày đăng');
@define ('_sanphamcungloai','Sản phẩm cùng loại');
@define ('_tinhuuich','Tin hữu ích');
@define ('_ykienkhachhang','Ý kiến khách hàng');
@define ('_dkdaily','Đăng ký làm đại lý');
//------------text--------------------------
@define ('_xemchitiet', 'Xem chi tiết');
@define ('_tatcaytuong', 'Tất cả ý tưởng');
@define ('_motasanpham', 'Mô tả sản phẩm');
@define ('_quycach', 'Quy cách');
@define ('_huongdanbaoquan', 'Hướng dẫn bảo quản');
@define ('_diachi', 'Địa chỉ');
@define ('_ngayhoanthanh', 'Ngày hoàn thành');
@define ('_dangchuyentrang', 'Đang chuyển trang');
@define ('_gia','Giá');
@define ('_giaban','Giá Bán');
@define ('_chinhsach','Chính sách');
@define ('_themvaogio','Thêm vào giỏ');
@define ('_themvaogiohang','Thêm vào giỏ hàng');
@define ('_luotxem','Lượt xem');
@define ('_soluong','Số lượng');
@define ('_muangaysanphamnay','Mua ngay sản phẩm này');
@define ('_camkethangchinhhangthat100','Cam kết hàng chính hãng, thật 100%');
@define ('_donvitinh','Đơn vị tính');
@define ('_goingay','Gọi ngay');
@define ('_decoduocgiatotnhat','Để có được giá tốt nhất');
@define ('_thongtin','Thông tin');
@define ('_danhgia','Đánh giá');
@define ('_masanpham','Mã sản phẩm');
@define ('_thanhcong','Thành công');
@define ('_donhanghoantat','Đơn hàng hoàn tất');
@define ('_giohang','Giỏ hàng');
@define ('_payment','Thanh toán');
@define ('_pname','Tên sản phẩm');
@define ('_quantity','Số lượng');
@define ('_total_price','Tổng giá');
@define ('_price','Giá bán');
@define('_congcu','Công Cụ');
@define ('_cus_info','Thông tin khách hàng');
@define ('_fullname','Họ tên');
@define ('_phone','Điện thoại');
@define ('_address','Địa chỉ');
@define ('_ghichu','Ghi chú');
@define ('_continue','Tiếp tục');
@define ('_thongtinnhanhang','Thông tin nhận hàng');
@define ('_gingthongtinnguoinhan','Giống thông tin người nhận');
@define ('_thanhtien', 'Thành tiền');
@define ('_xacnhanthanhtoan','Xác nhận và thanh toán');
@define ('_chuaduocgui','Đơn hàng của bạn chưa được gửi');
@define ('_dienthongtin','Vui lòng điền đầy đủ thông tin lại');
@define ('_camon','Xin Cảm ơn');
@define ('_bandadathangthanhcong','Bạn đã đặt hàng thành công.');
@define ('_chungtoiselienhe','Chúng tôi sẽ liên hệ với bạn sớm nhất.');
@define ('_madonhang','Mã đơn hàng là');
@define ('_xinloiquykhach','Xin lỗi quý khách.');
@define ('_hethongbiloixinthulai','Hệ thống bị lỗi, xin quý khách thử lại.');
@define ('_donhangchuacosanpham','Đơn hàng của bạn chưa có sản phẩm.');
@define ('_chonsanphamdemuahang','Vui lòng chọn sản phẩm để đặt hàng.');
@define ('_chuamuasanpham','Bạn chưa mua sản phẩm nào.Vui lòng chọn mua sản phẩm.');

@define ('_thongtinthanhtoan','Thông tin thanh toán');
@define ('_phuongthucthanhtoan','Phương thức thanh toán');
@define ('_muatiep','Mua tiếp');
@define ('_xoatatca','Xóa tất cả');

@define ('_dathangthanhcong','Đặt hàng thành công');
@define ('_camonquykhachdadathangtai','Cảm ơn quý khách đã đặt hàng tại');
@define ('_masodonhangcuabanla','Mã số đơn hàng của bạn là');
@define ('_tieptucmuahang','Tiếp tục mua hàng');
@define ('_dienthoaihotromuahang','Điện thoại hỗ trợ mua hàng');
@define ('_themsanpham','Thêm sản phẩm');
@define ('_vaogiohangthanhcong','vào giỏ thành công');
@define ('_thongtindonhangduocguivemail','Thông tin chi tiết về đơn hàng đã được gửi đến địa chỉ email bạn dùng để đặt hàng . Nếu không tìm thấy vui lòng kiểm tra trong hộp thư Spam hoặc Junk Folder');
//-------------form ------------------

@define ('_hovaten','Họ và tên');
@define ('_dienthoai','Điện thoại');
@define ('_noidung','Nội dung');
@define ('_tinhthanhpho','Tỉnh / Thành phố');
@define ('_quanhuyen','Quận huyện');
@define ('_guilienhe','Gửi liên hệ');
@define ('_gui','Gửi');
@define ('_nhaphoten','Nhập họ tên');
@define ('_nhapemail','Nhập Email');
@define ('_nhapfile','Nhập file');
@define ('_emailkhonghople','Email không hợp lệ');
@define ('_emaildadangky','Email đã đăng ký');
@define ('_nhapsodienthoai','Nhập số điện thoại');
@define ('_sodienthoaikhonghople','Số điện thoại không hợp lệ');

@define ('_chontinhthanhpho','Chọn tỉnh/thành phố');
@define ('_chonquanhuyen','Chọn quận/huyện');
@define ('_nhapdiachi','Xin nhập Địa chỉ');

@define ('_chondichvu','Chọn dịch vụ');
@define ('_nhapnoidung','Nhập nội dung');
@define ('_chuanhapduthongtin','Bạn chưa nhập đủ thông tin');
@define ('_guithuthanhcong','Thông tin đã được gửi thành công.<br /> Xin cảm ơn quý khách');
@define ('_guithuthatbai','Hệ thống đang xảy ra lỗi. Xin quý khách vui lòng thử lại sau');
@define ('_maxacnhankhongchinhxac','Mã xác nhận không chính xác!');
@define ('_clickvaodayneukhongmuondoilau','Click vào đây nếu không muốn đợi lâu');

//----------------box-right----------------
@define ('_guitinnhan','Gửi tin nhắn');
@define ('_goichochungtoi','Gọi cho chúng tôi');
@define ('_chatqua','Chat qua');
@define ('_vanphong','Văn phòng');
@define ('_hotlinetuvan','Hotline tư vấn');
@define ('_delaithongtin','Để lại thông tin');
@define ('_nhangiauudai','Nhận giá ưu đãi');
@define ('_sodienthoaicuaban','Số điện thoại của bạn');
@define ('_yeucaugoilai','Yêu cầu gọi lại');
@define ('_delailoinhanchochungtoi','Để lại lời nhắn cho chúng tôi');
@define ('_goicho','Gọi cho');
@define ('_denhantuvantotnhat','để nhận tư vấn tốt nhất');
@define ('_hoac','Hoặc');
@define ('_thongbaosetudongtatsau','Thông báo sẽ tự động tắt sau');
@define ('_giay','giây');
@define ('_guithanhcong','Gửi liên hệ thành công');
@define ('_loicamon','Cảm ơn bạn đã để lại thông tin. Chúng tôi sẽ liên hệ với bạn trong thời gian sớm nhất.');
@define ('_hethongbiloi','Hệ thống xảy ra lỗi');
@define ('_quykhachtimlaisau','Xin quý khách hãy thử lại sau.');
@define ('_thongbaokhachguiyeucaugoilai','Thông báo khách gửi yêu cầu gọi lại');
@define ('_sodienthoai','Số điện thoại');
@define ('_thoigiangui','Thời gian gửi');
@define ('_thongbaokhachguitinnhan','Thông báo khách gửi tin nhắn');
@define ('_tinnhan','Tin nhắn');
@define ('_goidien','Gọi điện');
?>